[tool.poetry]
name = "dep-tools"
version = "0.1.0"
description = ""
authors = ["Jesse Anderson <jesse.anderson@gmail.com>"]
license = "MIT"
packages = [{include = "dep_tools"}]
include = ["*.gpkg"]

[tool.poetry.dependencies]
python = "^3.8"
azure-storage-blob = "*"
geopandas = "*"
dask = {extras = ["complete"], version = "*"}
dask-gateway = "*"
geocube = "*"
gdal = "*"
pystac-client = "*"
planetary-computer = "*"
pygeos = "*"
rioxarray = "*"
stackstac = "*"
retry = "*"
tqdm = "*"
xarray = "*"

[tool.poetry.group.dev.dependencies]
pynvim = "^0.4.3"
black = "^23.1.0"
neovim = "^0.3.1"
pylint = "^2.17.1"
mypy = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
