[tool.poetry]
name = "dep-tools"
version = "0.1.0"
description = ""
authors = ["Jesse Anderson <jesse.anderson@gmail.com>"]
license = "MIT"
packages = [{include = "dep_tools"}]
include = ["*.gpkg"]

[tool.poetry.dependencies]
python = "^3.8"
azure-storage-blob = "*"
geopandas = "*"
dask = {extras = ["complete"], version = "*"}
dask-gateway = "*"
geocube = "*"
gdal = "*"
pystac-client = "*"
planetary-computer = "*"
rioxarray = "*"
stackstac = "*"
retry = "*"
tqdm = "*"
urlpath = "*"
xarray = "*"
rio-stac = "^0.8.0"
odc-stac = {git = "https://github.com/jessjaco/odc-stac.git", rev = "exception-fix"}
odc-algo = {git = "https://github.com/opendatacube/odc-algo.git", rev = "add-rust-geomedian-impl"}

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pylint = "^2.17.1"
mypy = "^1.1.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
