[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["dependencies"]
license = {file = "LICENSE"}
name = "dep-tools"
requires-python = ">=3.10"
version = "0.2.0"